### ISSUE TITLE
 New issue Native crash in SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by Wolftein** [square/okhttp#1338]
Using OkHTTP 2.2.0 and CyanogenMod v11 M1.
```
01-19 13:18:46.390: A/libc(29229): invalid address or address of corrupt block 0x4ca9a688 passed to dlfree
01-19 13:18:46.390: A/libc(29229): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 29341 (Thread-510)
01-19 13:18:46.490: I/DEBUG(138): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-19 13:18:46.490: I/DEBUG(138): Build fingerprint: 'K-Touch/CM_KT_S5/KT_S5:4.4.4/FTZ/14B0709112658:userdebug/test-keys'
01-19 13:18:46.490: I/DEBUG(138): Revision: '0'
01-19 13:18:46.490: I/DEBUG(138): pid: 29229, tid: 29341, name: Thread-510  >>> me.siegenthaler.utone.spotify <<<
01-19 13:18:46.490: I/DEBUG(138): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
01-19 13:18:46.490: I/DEBUG(138): Abort message: 'invalid address or address of corrupt block 0x4ca9a688 passed to dlfree'
01-19 13:18:46.720: I/DEBUG(138):     r0 00000000  r1 4034fe6b  r2 deadbaad  r3 403539ef
01-19 13:18:46.720: I/DEBUG(138):     r4 4ca9a688  r5 4035e180  r6 4000f000  r7 4ca9a690
01-19 13:18:46.720: I/DEBUG(138):     r8 517c8b0c  r9 4cb22b24  sl 4c87e9e8  fp 517c8b24
01-19 13:18:46.720: I/DEBUG(138):     ip 00000001  sp 517c8aa8  lr 403215e7  pc 403215e8  cpsr 600d0030
01-19 13:18:46.720: I/DEBUG(138):     d0  2064657372666c64  d1  2073736572646461
01-19 13:18:46.720: I/DEBUG(138):     d2  657264646120726f  d3  6f6320666f207373
01-19 13:18:46.720: I/DEBUG(138):     d4  0032006100640065  d5  0064006200630033
01-19 13:18:46.720: I/DEBUG(138):     d6  0037006200300066  d7  0037003800350035
01-19 13:18:46.720: I/DEBUG(138):     d8  0000000000000000  d9  0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d10 0000000000000000  d11 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d12 0000000000000000  d13 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d14 0000000000000000  d15 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d16 0000000000000000  d17 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d18 0000000000000000  d19 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     d20 ff004f8c4e8c508c  d21 000000000000001f
01-19 13:18:46.720: I/DEBUG(138):     d22 0010001000100010  d23 0000000000000020
01-19 13:18:46.720: I/DEBUG(138):     d24 0000000000000020  d25 0000000000000009
01-19 13:18:46.720: I/DEBUG(138):     d26 0000000000000000  d27 0000000000000001
01-19 13:18:46.720: I/DEBUG(138):     d28 ff00280028002e00  d29 0000000000000004
01-19 13:18:46.720: I/DEBUG(138):     d30 0000000000000000  d31 0000000000000000
01-19 13:18:46.720: I/DEBUG(138):     scr 68000010
01-19 13:18:46.790: I/DEBUG(138): backtrace:
01-19 13:18:46.790: I/DEBUG(138):     #00  pc 000115e8  /system/lib/libc.so (dlfree+1191)
01-19 13:18:46.790: I/DEBUG(138):     #01  pc 0000db67  /system/lib/libc.so (free+10)
01-19 13:18:46.790: I/DEBUG(138):     #02  pc 000836c3  /system/lib/libcrypto.so (CRYPTO_free+34)
01-19 13:18:46.790: I/DEBUG(138):     #03  pc 00027049  /system/lib/libssl.so (SSL_CTX_set_alpn_protos+16)
01-19 13:18:46.790: I/DEBUG(138):     #04  pc 00008b83  /system/lib/libjavacrypto.so
01-19 13:18:46.790: I/DEBUG(138):     #05  pc 0001ea10  /system/lib/libdvm.so (dvmPlatformInvoke+116)
01-19 13:18:46.790: I/DEBUG(138):     #06  pc 0004c3c7  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
01-19 13:18:46.790: I/DEBUG(138):     #07  pc 00027ea0  /system/lib/libdvm.so
01-19 13:18:46.790: I/DEBUG(138):     #08  pc 0002cdf0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+144)
01-19 13:18:46.790: I/DEBUG(138):     #09  pc 0002bf0c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+252)
01-19 13:18:46.800: I/DEBUG(138):     #10  pc 0005e707  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+338)
01-19 13:18:46.800: I/DEBUG(138):     #11  pc 0005e72b  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
01-19 13:18:46.800: I/DEBUG(138):     #12  pc 00053453  /system/lib/libdvm.so
01-19 13:18:46.800: I/DEBUG(138):     #13  pc 0000d248  /system/lib/libc.so (__thread_entry+72)
01-19 13:18:46.800: I/DEBUG(138):     #14  pc 0000d4e0  /system/lib/libc.so (pthread_create+508)
01-19 13:18:46.800: I/DEBUG(138): stack:
01-19 13:18:46.800: I/DEBUG(138):          517c8a68  484f1fed  /system/lib/libjavacrypto.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a6c  40ad4bec  /system/lib/libcrypto.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a70  00000006  
01-19 13:18:46.800: I/DEBUG(138):          517c8a74  7439850c  
01-19 13:18:46.800: I/DEBUG(138):          517c8a78  4ca9a688  
01-19 13:18:46.800: I/DEBUG(138):          517c8a7c  4035e180  
01-19 13:18:46.800: I/DEBUG(138):          517c8a80  4000f000  
01-19 13:18:46.800: I/DEBUG(138):          517c8a84  4032294d  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a88  4034fe6b  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a8c  517c8a9c  [stack:29341]
01-19 13:18:46.800: I/DEBUG(138):          517c8a90  403539ef  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a94  403215e7  /system/lib/libc.so (dlfree+1190)
01-19 13:18:46.800: I/DEBUG(138):          517c8a98  4034fe6b  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8a9c  4ca9a688  
01-19 13:18:46.800: I/DEBUG(138):          517c8aa0  403539ef  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8aa4  c0000000  
01-19 13:18:46.800: I/DEBUG(138):     #00  517c8aa8  4035a000  /system/lib/libc.so
01-19 13:18:46.800: I/DEBUG(138):          517c8aac  4ca9a690  
01-19 13:18:46.800: I/DEBUG(138):          517c8ab0  0000711c  
01-19 13:18:46.800: I/DEBUG(138):          517c8ab4  40af9e64  /system/lib/libcrypto.so
01-19 13:18:46.800: I/DEBUG(138):          517c8ab8  4cb22b30  
01-19 13:18:46.800: I/DEBUG(138):          517c8abc  4031db69  /system/lib/libc.so (free+12)
01-19 13:18:46.800: I/DEBUG(138):     #01  517c8ac0  23600005  
01-19 13:18:46.800: I/DEBUG(138):          517c8ac4  40a996c5  /system/lib/libcrypto.so (CRYPTO_free+36)
01-19 13:18:46.800: I/DEBUG(138):     #02  517c8ac8  00000018  
01-19 13:18:46.800: I/DEBUG(138):          517c8acc  502094f0  
01-19 13:18:46.800: I/DEBUG(138):          517c8ad0  41a3e600  /dev/ashmem/dalvik-heap (deleted)
01-19 13:18:46.800: I/DEBUG(138):          517c8ad4  40b2904d  /system/lib/libssl.so (SSL_CTX_set_alpn_protos+20)
01-19 13:18:46.810: I/DEBUG(138): memory near r1:
01-19 13:18:46.810: I/DEBUG(138):     4034fe48 74707572 206e6f69 65746564 64657463  
01-19 13:18:46.810: I/DEBUG(138):     4034fe58 20796220 6c007325 5f636269 6c6c616d  
01-19 13:18:46.810: I/DEBUG(138):     4034fe68 6900636f 6c61766e 61206469 65726464  
01-19 13:18:46.810: I/DEBUG(138):     4034fe78 6f207373 64612072 73657264 666f2073  
01-19 13:18:46.810: I/DEBUG(138):     4034fe88 726f6320 74707572 6f6c6220 25206b63  
01-19 13:18:46.810: I/DEBUG(138):     4034fe98 61702070 64657373 206f7420 6d007325  
01-19 13:18:46.810: I/DEBUG(138):     4034fea8 73207861 65747379 7962206d 20736574  
01-19 13:18:46.810: I/DEBUG(138):     4034feb8 3125203d 0a756c30 73797300 206d6574  
01-19 13:18:46.810: I/DEBUG(138):     4034fec8 65747962 20202073 203d2020 6c303125  
01-19 13:18:46.810: I/DEBUG(138):     4034fed8 69000a75 7375206e 79622065 20736574  
01-19 13:18:46.810: I/DEBUG(138):     4034fee8 20202020 3125203d 0a756c30 61747300  
01-19 13:18:46.810: I/DEBUG(138):     4034fef8 63206b63 7572726f 6f697470 6564206e  
01-19 13:18:46.810: I/DEBUG(138):     4034ff08 74636574 25006465 64253a73 7361203a  
01-19 13:18:46.810: I/DEBUG(138):     4034ff18 74726573 206e6f69 22732522 69616620  
01-19 13:18:46.810: I/DEBUG(138):     4034ff28 0064656c 253a7325 25203a64 61203a73  
01-19 13:18:46.810: I/DEBUG(138):     4034ff38 72657373 6e6f6974 73252220 61662022  
01-19 13:18:46.810: I/DEBUG(138): memory near r3:
01-19 13:18:46.810: I/DEBUG(138):     403539cc 72616873 6c206465 61726269 000a7972  
01-19 13:18:46.810: I/DEBUG(138):     403539dc 65746e69 6c616e72 6c75625f 72665f6b  
01-19 13:18:46.810: I/DEBUG(138):     403539ec 64006565 6572666c 6d740065 6f6c6c61  
01-19 13:18:46.810: I/DEBUG(138):     403539fc 6d735f63 006c6c61 6c616d74 5f636f6c  
01-19 13:18:46.810: I/DEBUG(138):     40353a0c 6772616c 6c640065 6c6c616d 7400636f  
01-19 13:18:46.810: I/DEBUG(138):     40353a1c 725f7972 6c6c6165 635f636f 6b6e7568  
01-19 13:18:46.820: I/DEBUG(138):     40353a2c 73696400 65736f70 7568635f 61006b6e  
01-19 13:18:46.820: I/DEBUG(138):     40353a3c 735f6464 656d6765 7000746e 65706572  
01-19 13:18:46.820: I/DEBUG(138):     40353a4c 615f646e 636f6c6c 6c657200 65736165  
01-19 13:18:46.820: I/DEBUG(138):     40353a5c 756e755f 5f646573 6d676573 73746e65  
01-19 13:18:46.820: I/DEBUG(138):     40353a6c 746e6d00 2a746e65 74656720 65746e6d  
01-19 13:18:46.820: I/DEBUG(138):     40353a7c 4628746e 2a454c49 6e690029 74742074  
01-19 13:18:46.820: I/DEBUG(138):     40353a8c 6d616e79 28725f65 2c746e69 61686320  
01-19 13:18:46.820: I/DEBUG(138):     40353a9c 202c2a72 657a6973 0029745f 64696f76  
01-19 13:18:46.820: I/DEBUG(138):     40353aac 646e6520 6e657770 00292874 72616863  
01-19 13:18:46.820: I/DEBUG(138):     40353abc 6567202a 65737574 65687372 29286c6c  
01-19 13:18:46.820: I/DEBUG(138): memory near r4:
01-19 13:18:46.820: I/DEBUG(138):     4ca9a668 00000400 00000000 00000000 0000001b  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a678 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a688 4035e1d0 00000021 4035e1c8 4035e1c8  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a698 2f796470 08312e33 70747468 312e312f  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6a8 00000020 000003c2 00000001 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6b8 00000000 00000004 00000001 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6c8 00030000 000000f7 000000ac 00000001  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6d8 00000100 00000100 00000100 00030000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6e8 00030000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6f8 00030000 00010000 0000007b 00000056  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a708 00000001 00000080 00000080 00000080  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a718 00010000 00010000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a728 00000000 00040000 00004000 0000003d  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a738 0000002b 00000001 00000040 00000040  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a748 00000040 00004000 00004000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a758 00000000 00000000 00044000 00001000  
01-19 13:18:46.820: I/DEBUG(138): memory near r5:
01-19 13:18:46.820: I/DEBUG(138):     4035e160 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4035e170 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4035e180 83363fdc 0000dfcb 00000088 00003fd8  
01-19 13:18:46.820: I/DEBUG(138):     4035e190 4000f000 4e07c268 502d5000 00200000  
01-19 13:18:46.820: I/DEBUG(138):     4035e1a0 00000766 01e9e5c8 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4035e1b0 4035e1a8 4035e1a8 4035e1b0 4035e1b0  
01-19 13:18:46.820: I/DEBUG(138):     4035e1c0 4ca9ea20 4de83ad0 4df88688 4df88688  
01-19 13:18:46.820: I/DEBUG(138):     4035e1d0 4ca9a688 4ca9a688 4e090f08 4e090f08  
01-19 13:18:46.820: I/DEBUG(138):     4035e1e0 473b3ae8 473b3ae8 4e2f0fa0 4cb3ad98  
01-19 13:18:46.820: I/DEBUG(138):     4035e1f0 4ca0dc10 4de340e0 4c9def80 4c9def80  
01-19 13:18:46.820: I/DEBUG(138):     4035e200 4ded7930 4cb3a690 4df88408 4dfaa260  
01-19 13:18:46.820: I/DEBUG(138):     4035e210 4df836e0 4df836e0 4df22ed8 4df22ed8  
01-19 13:18:46.820: I/DEBUG(138):     4035e220 4c8e1210 4c8e1210 4850bb58 4850bb58  
01-19 13:18:46.820: I/DEBUG(138):     4035e230 4c8e10f0 4c8e10f0 4df83860 4ca21540  
01-19 13:18:46.820: I/DEBUG(138):     4035e240 4dfaa188 4dfaa188 4c5917b0 4c5917b0  
01-19 13:18:46.820: I/DEBUG(138):     4035e250 4ca21470 4ca21470 4ca0dd78 4ca0dd78  
01-19 13:18:46.820: I/DEBUG(138): memory near r6:
01-19 13:18:46.820: I/DEBUG(138):     4000efe0 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000eff0 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f000 00000000 0000200b 4850f248 0000003a  
01-19 13:18:46.820: I/DEBUG(138):     4000f010 48513695 00000034 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f020 00000000 00000000 4850cfac 0000002d  
01-19 13:18:46.820: I/DEBUG(138):     4000f030 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f040 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f050 48510a52 0000003c 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f060 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f070 00000000 00000000 48515e69 0000003a  
01-19 13:18:46.820: I/DEBUG(138):     4000f080 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f090 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f0a0 00000000 00000000 485151cc 0000002a  
01-19 13:18:46.820: I/DEBUG(138):     4000f0b0 4851111e 00000027 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4000f0c0 00000000 00000000 485105af 00000034  
01-19 13:18:46.820: I/DEBUG(138):     4000f0d0 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138): memory near r7:
01-19 13:18:46.820: I/DEBUG(138):     4ca9a670 00000000 0000001b 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a680 00000000 00000000 4035e1d0 00000021  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a690 4035e1c8 4035e1c8 2f796470 08312e33  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6a0 70747468 312e312f 00000020 000003c2  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6b0 00000001 00000000 00000000 00000004  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6c0 00000001 00000000 00030000 000000f7  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6d0 000000ac 00000001 00000100 00000100  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6e0 00000100 00030000 00030000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a6f0 00000000 00000000 00030000 00010000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a700 0000007b 00000056 00000001 00000080  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a710 00000080 00000080 00010000 00010000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a720 00000000 00000000 00000000 00040000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a730 00004000 0000003d 0000002b 00000001  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a740 00000040 00000040 00000040 00004000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a750 00004000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     4ca9a760 00044000 00001000 0000001e 00000015  
01-19 13:18:46.820: I/DEBUG(138): memory near r8:
01-19 13:18:46.820: I/DEBUG(138):     517c8aec 4c87ee30 23600005 41a3e600 4c87e9d8  
01-19 13:18:46.820: I/DEBUG(138):     517c8afc 476bafa8 4c87e9d8 416b0a14 23600005  
01-19 13:18:46.820: I/DEBUG(138):     517c8b0c 416d93ad 4cb22b24 00000001 415a9257  
01-19 13:18:46.820: I/DEBUG(138):     517c8b1c 418fc980 00000008 416de3cb 4cb22b24  
01-19 13:18:46.820: I/DEBUG(138):     517c8b2c 415a9254 484f3b55 4c87e9e8 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b3c 00000000 2c300001 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b4c 4035e384 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b5c 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b6c 00000000 4c87e9d8 475298f8 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b7c 00000000 417442a8 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8b8c 416f0a19 00000000 00000000 4cb22a6c  
01-19 13:18:46.820: I/DEBUG(138):     517c8b9c 4035e384 41935d50 417dfd58 41a3e678  
01-19 13:18:46.820: I/DEBUG(138):     517c8bac 7439850c 417dfd58 4035e384 41a3e6d8  
01-19 13:18:46.820: I/DEBUG(138):     517c8bbc 416f50cb 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8bcc 00000000 00000000 00000000 00000000  
01-19 13:18:46.820: I/DEBUG(138):     517c8bdc 7439850c 4173cc6c 7439850c 00000018  
01-19 13:18:46.820: I/DEBUG(138): memory near r9:
01-19 13:18:46.820: I/DEBUG(138):     4cb22b04 00000000 4cb22b44 41596ed0 4cb22b44  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b14 41596f04 476bafa8 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b24 502094f0 00000000 23600005 4cb22bfc  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b34 4ecd6754 47529c78 41596f04 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b44 502094f0 00000000 41a3e5f0 417caa48  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b54 00000000 41a3dc38 41a3e4f8 00000001  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b64 4ecd7ce2 477c3028 4edd722a 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b74 00000001 41a3e4f8 41c64f98 41a3e218  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b84 417ef278 00000001 00000000 41c65020  
01-19 13:18:46.830: I/DEBUG(138):     4cb22b94 41a3dc38 41a39ef0 00000001 4cb22bfc  
01-19 13:18:46.830: I/DEBUG(138):     4cb22ba4 4ecd674e 4772f5e8 4ecd7ce2 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4cb22bb4 41c79290 00000000 41a3dc38 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4cb22bc4 00000400 000001bb 41c79300 502094f0  
01-19 13:18:46.830: I/DEBUG(138):     4cb22bd4 00000000 00000000 41a324c0 41a3dc38  
01-19 13:18:46.830: I/DEBUG(138):     4cb22be4 41a3dc38 4cb22c48 4ecd6a94 477c8e68  
01-19 13:18:46.830: I/DEBUG(138):     4cb22bf4 4ecd6754 00000000 41a3d1b8 00003a98  
01-19 13:18:46.830: I/DEBUG(138): memory near sl:
01-19 13:18:46.830: I/DEBUG(138):     4c87e9c8 4c76b7b8 00000000 00000018 0000045b  
01-19 13:18:46.830: I/DEBUG(138):     4c87e9d8 485964c0 4cb22b24 47529c78 40051000  
01-19 13:18:46.830: I/DEBUG(138):     4c87e9e8 4c5915c8 00000000 517c8c40 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4c87e9f8 517c8c94 0000001b 00000000 416b0b80  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea08 00000000 00000000 468d6870 4cb1f300  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea18 00000000 00000000 00000001 00004000  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea28 00000000 4c87ee50 416b0b80 416b5ac0  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea38 00000000 416b9bbc 416b9c30 416b9ae0  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea48 416b9b00 416b9b5c 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea58 4c689070 00000028 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea68 00000000 00000006 00002000 417419fc  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea78 00000000 473e2c58 00000002 4c87f098  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea88 00000001 00000040 00000200 00000004  
01-19 13:18:46.830: I/DEBUG(138):     4c87ea98 00000003 4859f13e 4859f13e 00000006  
01-19 13:18:46.830: I/DEBUG(138):     4c87eaa8 4859f14a 47413800 d4b8ed6a 89444642  
01-19 13:18:46.830: I/DEBUG(138):     4c87eab8 a2c0fede eff657ad 5d9c9469 4a34cc78  
01-19 13:18:46.830: I/DEBUG(138): memory near fp:
01-19 13:18:46.830: I/DEBUG(138):     517c8b04 416b0a14 23600005 416d93ad 4cb22b24  
01-19 13:18:46.830: I/DEBUG(138):     517c8b14 00000001 415a9257 418fc980 00000008  
01-19 13:18:46.830: I/DEBUG(138):     517c8b24 416de3cb 4cb22b24 415a9254 484f3b55  
01-19 13:18:46.830: I/DEBUG(138):     517c8b34 4c87e9e8 00000000 00000000 2c300001  
01-19 13:18:46.830: I/DEBUG(138):     517c8b44 00000000 00000000 4035e384 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b54 00000000 00000000 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b64 00000000 00000000 00000000 4c87e9d8  
01-19 13:18:46.830: I/DEBUG(138):     517c8b74 475298f8 00000000 00000000 417442a8  
01-19 13:18:46.830: I/DEBUG(138):     517c8b84 00000000 00000000 416f0a19 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b94 00000000 4cb22a6c 4035e384 41935d50  
01-19 13:18:46.830: I/DEBUG(138):     517c8ba4 417dfd58 41a3e678 7439850c 417dfd58  
01-19 13:18:46.830: I/DEBUG(138):     517c8bb4 4035e384 41a3e6d8 416f50cb 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8bc4 00000000 00000000 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8bd4 00000000 00000000 7439850c 4173cc6c  
01-19 13:18:46.830: I/DEBUG(138):     517c8be4 7439850c 00000018 417dfd58 475298f8  
01-19 13:18:46.830: I/DEBUG(138):     517c8bf4 41a3dc38 41a3e4f8 41a3e6d8 417442a8  
01-19 13:18:46.830: I/DEBUG(138): memory near sp:
01-19 13:18:46.830: I/DEBUG(138):     517c8a88 4034fe6b 517c8a9c 403539ef 403215e7  
01-19 13:18:46.830: I/DEBUG(138):     517c8a98 4034fe6b 4ca9a688 403539ef c0000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8aa8 4035a000 4ca9a690 0000711c 40af9e64  
01-19 13:18:46.830: I/DEBUG(138):     517c8ab8 4cb22b30 4031db69 23600005 40a996c5  
01-19 13:18:46.830: I/DEBUG(138):     517c8ac8 00000018 502094f0 41a3e600 40b2904d  
01-19 13:18:46.830: I/DEBUG(138):     517c8ad8 502094f0 41a3e600 00000004 484f3b87  
01-19 13:18:46.830: I/DEBUG(138):     517c8ae8 00000003 4c87ee30 23600005 41a3e600  
01-19 13:18:46.830: I/DEBUG(138):     517c8af8 4c87e9d8 476bafa8 4c87e9d8 416b0a14  
01-19 13:18:46.830: I/DEBUG(138):     517c8b08 23600005 416d93ad 4cb22b24 00000001  
01-19 13:18:46.830: I/DEBUG(138):     517c8b18 415a9257 418fc980 00000008 416de3cb  
01-19 13:18:46.830: I/DEBUG(138):     517c8b28 4cb22b24 415a9254 484f3b55 4c87e9e8  
01-19 13:18:46.830: I/DEBUG(138):     517c8b38 00000000 00000000 2c300001 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b48 00000000 4035e384 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b58 00000000 00000000 00000000 00000000  
01-19 13:18:46.830: I/DEBUG(138):     517c8b68 00000000 00000000 4c87e9d8 475298f8  
01-19 13:18:46.830: I/DEBUG(138):     517c8b78 00000000 00000000 417442a8 00000000  
01-19 13:18:46.830: I/DEBUG(138): code around pc:
01-19 13:18:46.830: I/DEBUG(138):     403215c8 6a014478 62021e4a f7fdb95a e008fd39  
01-19 13:18:46.830: I/DEBUG(138):     403215d8 4a2b482a 447a4478 f0014621 4a13f9ab  
01-19 13:18:46.830: I/DEBUG(138):     403215e8 49286014 f8d14479 079a31bc f501d51c  
01-19 13:18:46.830: I/DEBUG(138):     403215f8 e8bd70e0 f02c40f8 4823b859 f7fd4478  
01-19 13:18:46.830: I/DEBUG(138):     40321608 4822fd0d e7fa4478 42b7688f ae10f43f  
01-19 13:18:46.830: I/DEBUG(138):     40321618 481fe611 e7f24478 4478481e 6888e7ef  
01-19 13:18:46.840: I/DEBUG(138):     40321628 f43f4298 e606aed4 bf00bdf8 deadbaad  
01-19 13:18:46.840: I/DEBUG(138):     40321638 0003d02a 0003d01c 0003cf84 000327a9  
01-19 13:18:46.840: I/DEBUG(138):     40321648 0003cef8 0003cee6 0003ce6e 0003ce4c  
01-19 13:18:46.840: I/DEBUG(138):     40321658 0003cdf0 0003cdda 0003cd74 0003cd5c  
01-19 13:18:46.840: I/DEBUG(138):     40321668 0003cd4a 0003ccf4 0003cccc 0003cc46  
01-19 13:18:46.840: I/DEBUG(138):     40321678 0003cbec 0003cbd2 0003cbb4 0002e88b  
01-19 13:18:46.840: I/DEBUG(138):     40321688 0003240d 0003cb90 000323e7 000323df  
01-19 13:18:46.840: I/DEBUG(138):     40321698 000323cf 000323c9 460db538 b1704601  
01-19 13:18:46.840: I/DEBUG(138):     403216a8 0200ea45 f405fb00 04030c10 4620b143  
01-19 13:18:46.840: I/DEBUG(138):     403216b8 eecaf028 bf1842a8 34fff04f 4604e000  
01-19 13:18:46.840: I/DEBUG(138): code around lr:
01-19 13:18:46.840: I/DEBUG(138):     403215c4 482e61a3 6a014478 62021e4a f7fdb95a  
01-19 13:18:46.840: I/DEBUG(138):     403215d4 e008fd39 4a2b482a 447a4478 f0014621  
01-19 13:18:46.840: I/DEBUG(138):     403215e4 4a13f9ab 49286014 f8d14479 079a31bc  
01-19 13:18:46.840: I/DEBUG(138):     403215f4 f501d51c e8bd70e0 f02c40f8 4823b859  
01-19 13:18:46.840: I/DEBUG(138):     40321604 f7fd4478 4822fd0d e7fa4478 42b7688f  
01-19 13:18:46.840: I/DEBUG(138):     40321614 ae10f43f 481fe611 e7f24478 4478481e  
01-19 13:18:46.840: I/DEBUG(138):     40321624 6888e7ef f43f4298 e606aed4 bf00bdf8  
01-19 13:18:46.840: I/DEBUG(138):     40321634 deadbaad 0003d02a 0003d01c 0003cf84  
01-19 13:18:46.840: I/DEBUG(138):     40321644 000327a9 0003cef8 0003cee6 0003ce6e  
01-19 13:18:46.840: I/DEBUG(138):     40321654 0003ce4c 0003cdf0 0003cdda 0003cd74  
01-19 13:18:46.840: I/DEBUG(138):     40321664 0003cd5c 0003cd4a 0003ccf4 0003cccc  
01-19 13:18:46.840: I/DEBUG(138):     40321674 0003cc46 0003cbec 0003cbd2 0003cbb4  
01-19 13:18:46.840: I/DEBUG(138):     40321684 0002e88b 0003240d 0003cb90 000323e7  
01-19 13:18:46.840: I/DEBUG(138):     40321694 000323df 000323cf 000323c9 460db538  
01-19 13:18:46.840: I/DEBUG(138):     403216a4 b1704601 0200ea45 f405fb00 04030c10  
01-19 13:18:46.840: I/DEBUG(138):     403216b4 4620b143 eecaf028 bf1842a8 34fff04f  
01-19 13:18:46.840: I/DEBUG(138): memory map around fault addr deadbaad:
01-19 13:18:46.840: I/DEBUG(138):     beb86000-beba7000 rw- [stack]
01-19 13:18:46.840: I/DEBUG(138):     (no map for address)
01-19 13:18:46.840: I/DEBUG(138):     ffff0000-ffff1000 r-x [vectors]
```

**Comment by swankjesse** [comment]
Looks like we need to disable ALPN on Android 4.4.x and earlier.
https://code.google.com/p/android/issues/detail?id=67940

**Comment by imort** [comment]
Looks like we have something related but I am not sure. After integrating OkHttp 2.2 (Retrofit 1.9 and regular download requests) we are receiving native crashes through HockeyApp. All devices (various) are KitKat. Our test devices with KitKat work normally and we could not reproduce this crash.

```
Android: 4.4.4
Manufacturer: motorola
Model: XT1097

Crash reason:  SIGSEGV
Crash address: 0xdeadbaad

Thread 30 (crashed)
 0  libc.so + 0x118b4
     r0 = 0x00000000    r1 = 0x400730d2    r2 = 0xdeadbaad    r3 = 0x40076d11
     r4 = 0x6e035c20    r5 = 0x40081190    r6 = 0x40021000    r7 = 0x6e035c28
     r8 = 0x6c5a5964    r9 = 0x6b8b2a7c   r10 = 0x6b8ad1b0   r12 = 0x00000001
     fp = 0x6c5a597c    sp = 0x6c5a5908    lr = 0x400448b3    pc = 0x400448b4
    Found by: given as instruction pointer in context
 1  libc.so + 0x118b1
     fp = 0x415aeef7    sp = 0x6c5a5984    lr = 0x6b8b2a7c    pc = 0x400448b3
    Found by: previous frame's frame pointer
 2  conscrypt.odex + 0x373da
     sp = 0x6c5a5988    pc = 0x638d63dc
    Found by: stack scanning
 3  libjavacrypto.so + 0x8bbf
     sp = 0x6c5a598c    pc = 0x6a7d4bc1
    Found by: stack scanning
...
```

Is there some kind of workaround? Should we disable SPDY or somehow disable ALPN? We can drop some speed improvements (our servers do not support SPDY) for better stability of the application.

**Comment by swankjesse** [comment]
Until we've deployed the fix, the workaround is to disable SPDY and HTTP/2.
```
    client.setProtocols(Collections.singletonList(Protocol.HTTP_1_1));
```

**Comment by imort** [comment]
Already found it. Thank you for confirmation

**Comment by imort** [comment]
Still have this on Samsung Galaxy Note II, after implementing
```
client.setProtocols(Collections.singletonList(Protocol.HTTP_1_1));
```

Can this help?
```
client.setConnectionSpecs(Arrays.asList(ConnectionSpec.COMPATIBLE_TLS, ConnectionSpec.CLEARTEXT));
```

**Comment by hzsweers** [comment]
Just wanted to mention we started getting a lot of native crashes with 2.2 as well in Flipboard. On the off chance it's related, here's what we got:

 ```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Verizon/kltevzw/kltevzw:4.4.4/KTU84P/G900VVRU1ANK2:user/release-keys'
Revision: '14'
pid: 3178, tid: 3497, name: Thread-22866 >>> flipboard.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: 'invalid address or address of corrupt block 0x85f320d0 passed to dlfree'
r0 00000000 r1 401031a2 r2 deadbaad r3 40106d43
r4 85f320d0 r5 40111190 r6 400b0000 r7 85f320d8
r8 00000003 r9 85fb705d sl 00000001 fp 85fb7061
ip 00000001 sp 7f14e9c8 lr 400d48cb pc 400d48cc cpsr 600f0030
d0 2064696c61766e69 d1 2073736572646461
d2 657264646120726f d3 6f6320666f207373
d4 0000000006000378 d5 0000000004000b92
d6 000000000500000e d7 000004000d000000
d8 40490fdb00000000 d9 4487000041a00000
d10 446b400044d4a000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 c0a7b8de5cdbbea4 d17 010001ff0d000013
d18 ed38a6fc57a0334b d19 8e5515ece9313a54
d20 ab20a8a53c8f3b91 d21 2ece2460c34be3f9
d22 cbc11f1337eac979 d23 078b8b1a06b7e853
d24 0068006700650066 d25 0069006a006a0069
d26 0000000000000000 d27 0000000000000000
d28 0048004700450046 d29 0049004a004a0049
d30 006a006a006a006a d31 0000000000000000
scr 68000013

backtrace:
#00 pc 000118cc /system/lib/libc.so (dlfree+1191)
#01 pc 0000dd4f /system/lib/libc.so (free+10)
#02 pc 000824a5 /system/lib/libcrypto.so (CRYPTO_free+24)
#03 pc 0002aaf9 /system/lib/libssl.so (ssl_parse_serverhello_tlsext+244)
#04 pc 00016bd9 /system/lib/libssl.so (ssl3_get_server_hello+924)
#05 pc 000196db /system/lib/libssl.so (ssl3_connect+642)
#06 pc 00024fc9 /system/lib/libssl.so (SSL_do_handshake+72)
#07 pc 0000c6a9 /system/lib/libjavacrypto.so
#08 pc 00020e8c /system/lib/libdvm.so (dvmPlatformInvoke+112)
#09 pc 00051b2f /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
#10 pc 0002a320 /system/lib/libdvm.so
#11 pc 000317d0 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#12 pc 0002ee68 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#13 pc 00063f9d /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
#14 pc 00063fc1 /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
#15 pc 00058c93 /system/lib/libdvm.so
#16 pc 0000d290 /system/lib/libc.so (__thread_entry+72)
#17 pc 0000d428 /system/lib/libc.so (pthread_create+240)

code around pc:
400d48ac 6a014478 62021e4a f7fdb95a e008fd39 
400d48bc 4621482a 44784a2a f001447a 4a13f9b3 
400d48cc 49286014 f8d14479 079a31bc f501d51c 
400d48dc e8bd70e0 f02c40f8 4823b889 f7fd4478 
400d48ec 4822fd0d e7fa4478 42b7688f ae10f43f 
400d48fc 481fe611 e7f24478 4478481e 6888e7ef 
400d490c f43f4298 e606aed4 bf00bdf8 deadbaad 
400d491c 0003cd56 0003cd48 0003ccb0 00032819 
400d492c 0003cc24 0003cc12 0003cb9a 0003cb78 
400d493c 0003cb1c 0003cb06 0003caa0 0003ca88 
400d494c 0003ca76 0003ca1e 0003c9f8 0003c96e 
400d495c 0003c918 0003c8fe 0003c8e0 0002e8dc 
400d496c 0003247b 0003c8bc 00032457 0003244f 
400d497c 0003243f 00032439 460db538 b1704601 
400d498c 0200ea45 f405fb00 04030c10 4620b143 
400d499c ef18f028 bf1842a8 34fff04f 4604e000 

code around lr:
400d48a8 482e61a3 6a014478 62021e4a f7fdb95a 
400d48b8 e008fd39 4621482a 44784a2a f001447a 
400d48c8 4a13f9b3 49286014 f8d14479 079a31bc 
400d48d8 f501d51c e8bd70e0 f02c40f8 4823b889 
400d48e8 f7fd4478 4822fd0d e7fa4478 42b7688f 
400d48f8 ae10f43f 481fe611 e7f24478 4478481e 
400d4908 6888e7ef f43f4298 e606aed4 bf00bdf8 
400d4918 deadbaad 0003cd56 0003cd48 0003ccb0 
400d4928 00032819 0003cc24 0003cc12 0003cb9a 
400d4938 0003cb78 0003cb1c 0003cb06 0003caa0 
400d4948 0003ca88 0003ca76 0003ca1e 0003c9f8 
400d4958 0003c96e 0003c918 0003c8fe 0003c8e0 
400d4968 0002e8dc 0003247b 0003c8bc 00032457 
400d4978 0003244f 0003243f 00032439 460db538 
400d4988 b1704601 0200ea45 f405fb00 04030c10 
400d4998 4620b143 ef18f028 bf1842a8 34fff04f 
```

**Comment by nfuller** [comment]
@hzsweers - I'm no expert but that looks like it might be something else (SSL_CTX_set_alpn_protos isn't mentioned).

I think it may be this: https://code.google.com/p/android/issues/detail?id=74964

Please provide all the information you have about device / GMS core version / OS version.

**Comment by Wolftein** [comment]
I'm getting the same exeption than @hzsweers when downgraded to 2.1

**Comment by Papipo** [comment]
I get this on 2.2 and 2.1 when using Picasso to retrieve a jpg. It happens on Lollipop, on KitKat it works fine.

```
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8000000173 in tid 3407 (_25421615_n.jpg)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-22 23:14:59.670      952-952/? I/DEBUG﹕ Build fingerprint: 'generic_x86_64/sdk_google_phone_x86_64/generic_x86_64:5.0.1/LSX66B/1630668:eng/test-keys'
02-22 23:14:59.670      952-952/? I/DEBUG﹕ Revision: '0'
02-22 23:14:59.670      952-952/? I/DEBUG﹕ ABI: 'x86_64'
02-22 23:14:59.670      952-952/? I/DEBUG﹕ pid: 3382, tid: 3407, name: _25421615_n.jpg  >>> com.isasaweis.android <<<
02-22 23:14:59.670      952-952/? I/DEBUG﹕ signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8000000173
02-22 23:14:59.670      952-952/? I/DEBUG﹕ rax 0000000000000000  rbx 00000080000000c3  rcx 0000000000000081  rdx 0000000000000001
02-22 23:14:59.670      952-952/? I/DEBUG﹕ rsi 000000000000001e  rdi 00007f1587ba79b0
02-22 23:14:59.670      952-952/? I/DEBUG﹕ r8  000000000000014a  r9  0000000000000000  r10 0000000000000024  r11 0000000000000000
02-22 23:14:59.670      952-952/? I/DEBUG﹕ r12 00007f157b5b40b0  r13 0000000000000000  r14 00007f157b584698  r15 00007f157b5843c0
02-22 23:14:59.670      952-952/? I/DEBUG﹕ cs  0000000000000033  ss  000000000000002b
02-22 23:14:59.670      952-952/? I/DEBUG﹕ rip 00007f158e6fd4d6  rbp 00007f157b584660  rsp 00007f157b4feb10  eflags 0000000000010206
02-22 23:14:59.670      952-952/? I/DEBUG﹕ backtrace:
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #00 pc 00000000000e34d6  /system/lib64/libcrypto.so (ENGINE_init+38)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #01 pc 00000000000eb435  /system/lib64/libcrypto.so (EVP_MD_CTX_copy_ex+37)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #02 pc 00000000000f8556  /system/lib64/libcrypto.so (HMAC_CTX_copy+22)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #03 pc 00000000000f7e32  /system/lib64/libcrypto.so
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #04 pc 00000000000f698a  /system/lib64/libcrypto.so (EVP_PKEY_CTX_dup+234)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #05 pc 00000000000eb52b  /system/lib64/libcrypto.so (EVP_MD_CTX_copy_ex+283)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #06 pc 000000000004a9b3  /system/lib64/libssl.so (tls1_mac+195)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #07 pc 0000000000032bf1  /system/lib64/libssl.so (ssl3_read_bytes+1249)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #08 pc 0000000000026acb  /system/lib64/libssl.so (ssl3_get_message+315)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #09 pc 00000000000263e2  /system/lib64/libssl.so (ssl3_get_finished+34)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #10 pc 0000000000028e90  /system/lib64/libssl.so (ssl3_connect+2256)
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #11 pc 00000000000186a2  /system/lib64/libjavacrypto.so
02-22 23:14:59.670      952-952/? I/DEBUG﹕ #12 pc 000000000040aac1  /data/dalvik-cache/x86_64/system@framework@boot.oat
```

**Comment by iNoles** [comment]
@Papipo " I'm no expert but that looks like it might be something else (SSL_CTX_set_alpn_protos isn't mentioned)."

**Comment by plinehan** [comment]
FWIW, we're still seeing crashes of this nature even after applying the @swankjesse workaround, though it appears much less prevalent.  Unfortunately, I haven't successfully reproed locally, so I only have minidumps which are missing system symbols.  As such I don't know the exact libssl/libcrypto functions that are causing the problem.

**Comment by imort** [comment]
We had this fixed by using 2.1 for now.

**Comment by plinehan** [comment]
Thanks @imort!  I rolled back to okhttp-2.1.0 (still using okio-1.2.0) and pushed to everyone and I'm no longer seeing the crash in the wild.

**Comment by swankjesse** [comment]
Fixed in 2.3 with https://github.com/square/okhttp/pull/1474

**Comment by ayjindal** [comment]
@swankjesse Could you please take a look at https://github.com/square/okhttp/issues/1520? The crash looks similar to this issue.

**Comment by ValleZ** [comment]
I still see it with okhttp 2.4 in android 4.4 only. Affected devices: Galaxy Tab4/Galaxy Alpha/Xperia M2 (D2303)/Aquaris E5/Galaxy Note II (t03g)

Build fingerprint: 'bq/Aquaris_E5/Aquaris_E5:4.4.4/KTU84P/1432699580:user/release-keys'
Revision: '0'
pid: 20955, tid: 21984, name: Thread-916 >>> com.asda.android <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: 'invalid address or address of corrupt block 0x61216c20 passed to dlfree'
r0 00000000 r1 400a73aa r2 deadbaad r3 400aaefa
r4 61216c20 r5 400b5190 r6 40062000 r7 61216c28
r8 0000000b r9 00000020 sl 00000004 fp 64bee059
ip 00000001 sp 6261f9c0 lr 400788b3 pc 400788b4 cpsr 600f0030
d0 2064657373617064 d1 6120726f2073736c
d2 6f20737365726466 d3 707572726f632072
d4 e3d5da9ec4bf5fe8 d5 e3dd1b7d2d54db6a
d6 96f4be675a6d9289 d7 ff0d000014c04598
d8 4409400000000225 d9 0000000043955d00
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 0000000000000000 d17 0000000000000000
d18 a484ddd5da219464 d19 3d19df4372867123
d20 00fe00fe00fe00fe d21 00fe00fe00fe00fe
d22 0000000000000000 d23 0000000000000000
d24 00fe00fe00fe00fe d25 00fe00fe00fe00fe
d26 0000000000000020 d27 0000000000000009
d28 00fe00fe00fe00fe d29 00fe00fe00fe00fe
d30 0000000000000000 d31 0000000000000000
scr 68000012

backtrace:
#00 pc 000118b4 /system/lib/libc.so (dlfree+1191)
#01 pc 0000dd53 /system/lib/libc.so (free+10)
#02 pc 00083943 /system/lib/libcrypto.so (CRYPTO_free+34)
#03 pc 0002f623 /system/lib/libssl.so (ssl_parse_serverhello_tlsext+738)
#04 pc 000181b1 /system/lib/libssl.so (ssl3_get_server_hello+1008)
#05 pc 000175af /system/lib/libssl.so (ssl3_connect+566)
#06 pc 00027ecb /system/lib/libssl.so (SSL_do_handshake+50)
#07 pc 0000aedd /system/lib/libjavacrypto.so
#08 pc 0002054c /system/lib/libdvm.so (dvmPlatformInvoke+112)
#09 pc 000511d7 /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
#10 pc 000299e0 /system/lib/libdvm.so
#11 pc 00030e6c /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#12 pc 0002e504 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#13 pc 00063639 /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
#14 pc 0006365d /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
#15 pc 0005833b /system/lib/libdvm.so
#16 pc 0000d2b8 /system/lib/libc.so (__thread_entry+72)
#17 pc 0000d450 /system/lib/libc.so (pthread_create+240)

code around pc:
40078894 6a014478 62021e4a f7fdb95a e008fd39 
400788a4 4621482a 44784a2a f001447a 4a13f9b3 
400788b4 49286014 f8d14479 079a31bc f501d51c 
400788c4 e8bd70e0 f02c40f8 4823b981 f7fd4478 
400788d4 4822fd0d e7fa4478 42b7688f ae10f43f 
400788e4 481fe611 e7f24478 4478481e 6888e7ef 
400788f4 f43f4298 e606aed4 bf00bdf8 deadbaad 
40078904 0003cd6e 0003cd60 0003ccc8 000329e8 
40078914 0003cc3c 0003cc2a 0003cbb2 0003cb90 
40078924 0003cb34 0003cb1e 0003cab8 0003caa0 
40078934 0003ca8e 0003ca36 0003ca10 0003c986 
40078944 0003c930 0003c916 0003c8f8 0002eafc 
40078954 0003264a 0003c8d4 00032626 0003261e 
40078964 0003260e 00032608 460db538 b1704601 
40078974 0200ea45 f405fb00 04030c10 4620b143 
40078984 e810f029 bf1842a8 34fff04f 4604e000 

code around lr:
40078890 482e61a3 6a014478 62021e4a f7fdb95a 
400788a0 e008fd39 4621482a 44784a2a f001447a 
400788b0 4a13f9b3 49286014 f8d14479 079a31bc 
400788c0 f501d51c e8bd70e0 f02c40f8 4823b981 
400788d0 f7fd4478 4822fd0d e7fa4478 42b7688f 
400788e0 ae10f43f 481fe611 e7f24478 4478481e 
400788f0 6888e7ef f43f4298 e606aed4 bf00bdf8 
40078900 deadbaad 0003cd6e 0003cd60 0003ccc8 
40078910 000329e8 0003cc3c 0003cc2a 0003cbb2 
40078920 0003cb90 0003cb34 0003cb1e 0003cab8 
40078930 0003caa0 0003ca8e 0003ca36 0003ca10 
40078940 0003c986 0003c930 0003c916 0003c8f8 
40078950 0002eafc 0003264a 0003c8d4 00032626 
40078960 0003261e 0003260e 00032608 460db538 
40078970 b1704601 0200ea45 f405fb00 04030c10 
40078980 4620b143 e810f029 bf1842a8 34fff04f 

Build fingerprint: 'samsung/mondrianwifixx/mondrianwifi:4.4.2/KOT49H/T320XXU1BOC1:user/release-keys'
Revision: '12'
pid: 3998, tid: 4066, name: Thread-14482 >>> com.asda.android <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
Abort message: 'invalid address or address of corrupt block 0x798699a8 passed to dlfree'
r0 00000000 r1 40077172 r2 deadbaad r3 4007ad22
r4 798699a8 r5 40085190 r6 41e9f000 r7 798699b0
r8 00000003 r9 7916305d sl 00000001 fp 79163061
ip 00000001 sp 7a3e59c8 lr 40048893 pc 40048894 cpsr 680f0030
d0 2064696c61766e69 d1 2073736572646461
d2 657264646120726f d3 6f6320666f207373
d4 0000000000000000 d5 0000000000000000
d6 0000000000000000 d7 000004003f800000
d8 4980000000100000 d9 0000000041b00000
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 3468becba27e6739 d17 01ff0d000014c044
d18 7cc74984374e408a d19 02bbfd58f5d7c440
d20 082040bda2ca32ad d21 4759d16027604ef7
d22 986bf8400c2ed0b0 d23 6739f9c5d144be7a
d24 0000000000010a14 d25 0000000000010a14
d26 0000000000000020 d27 0000000000000009
d28 0100010001000100 d29 0100010001000100
d30 3f3f3f2c3f3f3f2c d31 393f3917393f3917
scr 68000013

backtrace:
#00 pc 00011894 /system/lib/libc.so (dlfree+1191)
#01 pc 0000dd33 /system/lib/libc.so (free+10)
#02 pc 00082485 /system/lib/libcrypto.so (CRYPTO_free+24)
#03 pc 0002ac39 /system/lib/libssl.so (ssl_parse_serverhello_tlsext+244)
#04 pc 00016c5d /system/lib/libssl.so (ssl3_get_server_hello+924)
#05 pc 0001975f /system/lib/libssl.so (ssl3_connect+642)
#06 pc 00025109 /system/lib/libssl.so (SSL_do_handshake+72)
#07 pc 0000c6a9 /system/lib/libjavacrypto.so
#08 pc 00020bcc /system/lib/libdvm.so (dvmPlatformInvoke+112)
#09 pc 00051927 /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
#10 pc 0002a060 /system/lib/libdvm.so
#11 pc 00031510 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#12 pc 0002eba8 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#13 pc 00063e75 /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
#14 pc 00063e99 /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
#15 pc 00058b6b /system/lib/libdvm.so
#16 pc 0000d298 /system/lib/libc.so (__thread_entry+72)
#17 pc 0000d430 /system/lib/libc.so (pthread_create+240)

code around pc:
40048874 6a014478 62021e4a f7fdb95a e008fd39 
40048884 4621482a 44784a2a f001447a 4a13f9b3 
40048894 49286014 f8d14479 079a31bc f501d51c 
400488a4 e8bd70e0 f02c40f8 4823b88f f7fd4478 
400488b4 4822fd0d e7fa4478 42b7688f ae10f43f 
400488c4 481fe611 e7f24478 4478481e 6888e7ef 
400488d4 f43f4298 e606aed4 bf00bdf8 deadbaad 
400488e4 0003cd8e 0003cd80 0003cce8 00032830 
400488f4 0003cc5c 0003cc4a 0003cbd2 0003cbb0 
40048904 0003cb54 0003cb3e 0003cad8 0003cac0 
40048914 0003caae 0003ca56 0003ca30 0003c9a6 
40048924 0003c950 0003c936 0003c918 0002e8e4 
40048934 00032492 0003c8f4 0003246e 00032466 
40048944 00032456 00032450 460db538 b1704601 
40048954 0200ea45 f405fb00 04030c10 4620b143 
40048964 ef1ef028 bf1842a8 34fff04f 4604e000 

code around lr:
40048870 482e61a3 6a014478 62021e4a f7fdb95a 
40048880 e008fd39 4621482a 44784a2a f001447a 
40048890 4a13f9b3 49286014 f8d14479 079a31bc 
400488a0 f501d51c e8bd70e0 f02c40f8 4823b88f 
400488b0 f7fd4478 4822fd0d e7fa4478 42b7688f 
400488c0 ae10f43f 481fe611 e7f24478 4478481e 
400488d0 6888e7ef f43f4298 e606aed4 bf00bdf8 
400488e0 deadbaad 0003cd8e 0003cd80 0003cce8 
400488f0 00032830 0003cc5c 0003cc4a 0003cbd2 
40048900 0003cbb0 0003cb54 0003cb3e 0003cad8 
40048910 0003cac0 0003caae 0003ca56 0003ca30 
40048920 0003c9a6 0003c950 0003c936 0003c918 
40048930 0002e8e4 00032492 0003c8f4 0003246e 
40048940 00032466 00032456 00032450 460db538 
40048950 b1704601 0200ea45 f405fb00 04030c10 
40048960 4620b143 ef1ef028 bf1842a8 34fff04f
