### ISSUE TITLE
WebSocketCall IllegalStateException

### ISSUE THREAD

**Issue by tinsukE** [square/okhttp#1807]
Despite the "experimental" note on okhttp-ws page, I'm currently using it for an App with ~4.5k daily active users and I'm seeing some crash reports of:
```
Fatal Exception: java.lang.IllegalStateException
Unable to take ownership of connection.
```
at
```
com.squareup.okhttp.ws.WebSocketCall.createWebSocket (WebSocketCall.java:157)
```
I can see that there is a TODO in the source for this case (https://github.com/square/okhttp/blob/master/okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java#L155). Is the ws library still in development (as in: should I expect to see a fix soon)?

**Comment by JakeWharton** [comment]
That TODO is unrelated and deals with the fact that the code is in a
different package than the main library.

**Comment by JakeWharton** [comment]
Are you using version 2.4.0? The connection ownership stuff is mostly unknown to me so I'll have to talk/defer to @swankjesse about it. It may have also already been fixed as part of other work towards 2.5.0 which should be releasing soon.

**Comment by tinsukE** [comment]
Yes, I'm using the 2.4.0 version, but if there would be a potential fix for this on 2.5.0 I wouldn't mind waiting.

It is actually a rare crash, having happened 19 times on our current App version, which has already 243.157 sessions (~0,007% of the sessions crashed because of this issue).

If it is of any help, it only occurred so far on Samsung devices and on Lollipop ranging from version 5.0 to 5.1.1.

**Comment by atakankaya** [comment]
This issue is happening to us with much higher frequency. And not only Samsung but also HTC and LG devices also faced this. What is the status of this issue? Has it been fixed at 2.4.0?

**Comment by JakeWharton** [comment]
2.5.0 is latest, although the code is largely unchanged from what I
remember.

**Comment by swankjesse** [comment]
I believe this was also fixed with the new allocations model.
https://github.com/square/okhttp/pull/2045

**Comment by iceteahh** [comment]
It still happen on version 3.2.0. My app have 2k DAU and 300+ crashes last 30 day! How can I fix it?

**Comment by swankjesse** [comment]
@iceteahh please open a new issue with a stacktrace. If you have steps to reproduce, please include that also.
