### ISSUE TITLE
Call execute throws SecurityException

### ISSUE THREAD

**Issue by auchri** [square/okhttp#2283]
My app just crashed with the following exception:

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.execute(RealCall.java:57)
       at com.myapp.test.Loader.doRequest(Loader.java:312)
       at com.myapp.test.Loader.request(Loader.java:283)
       at com.myapp.test.Loader.getResponse(Loader.java:164)
       at com.myapp.test.Loader.getResponse(Loader.java:136)
       at com.myapp.test.Loader.executeSynchronous(Loader.java:117)
       at com.myapp.test.Loader.access$500(Loader.java:40)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:98)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:93)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.execute(RealCall.java:57)
       at com.myapp.test.Loader.doRequest(Loader.java:312)
       at com.myapp.test.Loader.request(Loader.java:283)
       at com.myapp.test.Loader.getResponse(Loader.java:164)
       at com.myapp.test.Loader.getResponse(Loader.java:136)
       at com.myapp.test.Loader.executeSynchronous(Loader.java:117)
       at com.myapp.test.Loader.access$500(Loader.java:40)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:98)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:93)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.system.ErrnoException: android_getaddrinfo failed: EACCES (Permission denied)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.execute(RealCall.java:57)
       at com.myapp.test.Loader.doRequest(Loader.java:312)
       at com.myapp.test.Loader.request(Loader.java:283)
       at com.myapp.test.Loader.getResponse(Loader.java:164)
       at com.myapp.test.Loader.getResponse(Loader.java:136)
       at com.myapp.test.Loader.executeSynchronous(Loader.java:117)
       at com.myapp.test.Loader.access$500(Loader.java:40)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:98)
       at com.myapp.test.Loader$1.doInBackground(Loader.java:93)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

At least, it should be documented that `execute()` can throw a security exception if someone removes the internet permission from the app with root.

**Comment by JakeWharton** [comment]
That is Android throwing, not OkHttp specifically. It would be weird to
document this as there's a whole slew of exceptions that can be thrown
because of Android.

**Comment by philipgiuliani** [comment]
I found the exact same issue in my Crashlytics today.  Its 100% on Android 5.1 devices only. So its maybe fixed in Android 6 i guess! Didnt happen that quite often so far :)

**Comment by istima** [comment]
same for us - there are a lot of users that are experiencing that problem. 
But it is not only 5.1, it is also on 4.+ and 6.+ :( 
Any ideas? Should we ignore that?

**Comment by philipgiuliani** [comment]
@istima this is already fixed in OkHttp 3.0!

**Comment by auchri** [comment]
@philipgiuliani As you can see in my stracktrace, I'm using OkHttp 3 - so it's not fixed.

**Comment by swankjesse** [comment]
@philipgiuliani could you provide us with an executable test case to reproduce the problem?

**Comment by hegazy** [comment]
I just found the same issue as well. It was 5.1.1.

**Comment by lftx** [comment]
finally, do you have resolved this?

**Comment by iNoles** [comment]
Did anyone checks with Android Manifest file for the Internet permissions?

**Comment by tenggangren** [comment]
finally, do you have resolved this??????????????

**Comment by lumin1914** [comment]
finally, do you have resolved this?????????????? how to resolved this???

**Comment by lumin1914** [comment]
finally, do you have resolved this?????????????? how to resolved this???

**Comment by yuCharles** [comment]
I have the same problem in 3.4.1
I called` chain.proceed(request)` in `public Response intercept(Chain chain)`
here is the code
```
public static class EncryptWallInterceptor implements Interceptor {

        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();
            Response response = chain.proceed(request);
            return response;
        }
    }
```
