### ISSUE TITLE
too many follow-up requests problem

### ISSUE THREAD

**Issue by MetaiR** [square/okhttp#3827]
hello,
recording to this [issue](https://github.com/square/retrofit/issues/2630) it looks like OkHttp has a problem with status code `408`.
just want to put it here to be fixed.

**Comment by yschimke** [comment]
There is changed handling of 408 in 3.10, which has not yet been released

https://github.com/square/okhttp/pull/3753

You could test with a snapshot.  But even if that doesn't help you can see examples in that PR of how to make a reproduction test case.

**Comment by MetaiR** [comment]
@yschimke 
something like this

> General:
Request URL:http://exampledomain:port/api
Request Method:GET
Status Code:408 
Remote Address:exampledomain:port
Referrer Policy:no-referrer-when-downgrade
----------
Response-Headers:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://example-server-ip:port
Access-Control-Expose-Headers:Set-Cookie
Content-Language:en
Content-Length:X
Content-Type:text/html;charset=utf-8
Date:Tue, 06 Feb 2018 23:12:09 GMT
Server:Apache TomEE
Vary:Origin

I'm not quite sure because we changed the status code but just status code and other things remained so it should like the above code (I copied the exact response from chrome, hope it's become useful)

**Comment by swankjesse** [comment]
Fixed in 3.10.

**Comment by aleeee** [comment]
it still happens on version 3.14.9
@Override
	public Request authenticate(Route route, Response response) throws IOException {
		// Request a new access token if needed
		if (!isTokenStillValid()) {
			try {
				getAccessToken();
			} catch (HttpException | ApiException e) {
				log.error("Error authenticating request {}", e.getMessage());
				throw new IOException(e.getCause());
			}
		}
		if(response.request().header("Authorization") != null && response.request().header("Authorization").equals(token.getValue()))
			return null;
		Request request = response.request().newBuilder().removeHeader("Authorization").build();
		
		return request.newBuilder().addHeader("Authorization", "Bearer " + token.getValue()).build();
		
	}

**Comment by aumarbello** [comment]
@aleeee Check out this solution: https://stackoverflow.com/a/63512049/8026243
