### ISSUE TITLE
IOException in DiskLruCache in 1.5.0.

### ISSUE THREAD

**Issue by chrisbanes** [square/okhttp#646]
Upgraded to v1.5.0 and I'm seeing a lot of these exceptions thrown.

```
java.lang.RuntimeException: java.io.IOException: failed to delete /data/data/app.philm.in/cache/picasso-cache/452f1b31c49eebbd77673818036d6560.0
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.io.IOException: failed to delete /data/data/app.philm.in/cache/picasso-cache/452f1b31c49eebbd77673818036d6560.0
       at com.squareup.okhttp.internal.DiskLruCache.remove(DiskLruCache.java:584)
       at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:639)
       at com.squareup.okhttp.internal.DiskLruCache.access$100(DiskLruCache.java:86)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:169)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by ibmkhd** [comment]
We are having the same issue using 
okhttp-urlconnection:2.1.0 , okhttp:2.1.0 and picasso:2.4.0.
It happened twice with a 4.3 Note 3.
```java
java.lang.RuntimeException: java.io.IOException: failed to delete /data/data/com.opensooq.OpenSooq/cache/picasso-cache/5243ac9aaec66b953ad21b26712379d6.0
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.io.IOException: failed to delete /data/data/com.opensooq.OpenSooq/cache/picasso-cache/5243ac9aaec66b953ad21b26712379d6.0
       at com.squareup.okhttp.internal.DiskLruCache.deleteIfExists(DiskLruCache.java:386)
       at com.squareup.okhttp.internal.DiskLruCache.removeEntry(DiskLruCache.java:600)
       at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:653)
       at com.squareup.okhttp.internal.DiskLruCache.access$100(DiskLruCache.java:85)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:167)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by aitorlape** [comment]
Same issue here on a Samsung Galaxy S3 and Android 4.2.2 and the following config

        compile 'com.squareup.picasso:picasso:2.4.0'
    	compile 'com.squareup.okhttp:okhttp:2.2.0'
    	compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
    	compile 'com.squareup.retrofit:retrofit:1.9.0'
		
    	java.lang.RuntimeException: java.io.IOException
		at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
		at java.lang.Thread.run(Thread.java:856)
	Caused by: java.io.IOException
		at com.squareup.okhttp.internal.DiskLruCache.renameTo(DiskLruCache.java:403)
		at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:383)
		at com.squareup.okhttp.internal.DiskLruCache.access$300(DiskLruCache.java:88)
		at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:171)
		... 3 more
	java.io.IOException
		at com.squareup.okhttp.internal.DiskLruCache.renameTo(DiskLruCache.java:403)
		at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:383)
		at com.squareup.okhttp.internal.DiskLruCache.access$300(DiskLruCache.java:88)
		at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:171)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
		at java.lang.Thread.run(Thread.java:856)

**Comment by rockerhieu** [comment]
Same here, still happen with okhttp-urlconnection:2.1.0 , okhttp:2.1.0 and picasso:2.4.0.

```
Fatal Exception: java.lang.RuntimeException
java.io.IOException
 raw
com.squareup.okhttp.internal.DiskLruCache$1.run (DiskLruCache.java:173)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080)
java.lang.Thread.run (Thread.java:838)
Caused by java.io.IOException
com.squareup.okhttp.internal.DiskLruCache.renameTo (DiskLruCache.java:395)
com.squareup.okhttp.internal.DiskLruCache.rebuildJournal (DiskLruCache.java:375)
com.squareup.okhttp.internal.DiskLruCache.access$300 (DiskLruCache.java:85)
com.squareup.okhttp.internal.DiskLruCache$1.run (DiskLruCache.java:169)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080)
java.lang.Thread.run (Thread.java:838)
```

@swankjesse should we reopen this issue?

**Comment by swankjesse** [comment]
@rockerhieu try upgrading your OkHttp to the release that has the fix first!

**Comment by swankjesse** [comment]
(We've fixed cache bugs since 2.1.0.)

**Comment by rockerhieu** [comment]
@swankjesse but as I mentioned, the issue still happen on version 2.1.0.

**Comment by parkjaeiek** [comment]
i got same probleam
okhttp 2.5.0 picasso 1.9.0

this error

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/data/com.vitalhint.haemukja/cache/picasso-cache/journal.tmp to /data/data/com.vitalhint.haemukja/cache/picasso-cache/journal
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
       at java.lang.Thread.run(Thread.java)
Caused by java.io.IOException: failed to rename /data/data/com.vitalhint.haemukja/cache/picasso-cache/journal.tmp to /data/data/com.vitalhint.haemukja/cache/picasso-cache/journal
       at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java)
       at com.squareup.okhttp.internal.DiskLruCache.access$400(DiskLruCache.java)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java)
       at java.lang.Thread.run(Thread.java)

**Comment by kaeawc** [comment]
I'm seeing a similar error as what @parkjaeiek found, same versions of Picasso `1.9.0` and OkHttp `2.5.0`:

```
0 java.lang.RuntimeException: java.io.IOException: failed to delete /data/data/co.hinge.mobile.android/cache/picasso-cache/cc45f6004dd1f99955745fd84140bb80.1
1 	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
2 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
3 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
4 	at java.lang.Thread.run(Thread.java:818)
5 Caused by: java.io.IOException: failed to delete /data/data/co.hinge.mobile.android/cache/picasso-cache/cc45f6004dd1f99955745fd84140bb80.1
6 	at com.squareup.okhttp.internal.io.FileSystem$1.delete(FileSystem.java:70)
7 	at com.squareup.okhttp.internal.DiskLruCache.removeEntry(DiskLruCache.java:607)
8 	at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:664)
9 	at com.squareup.okhttp.internal.DiskLruCache.access$200(DiskLruCache.java:88)
10 	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
11 	... 3 more
```

**Comment by metcorne** [comment]
Any solution? I have the same crash as @parkjaeiek a couple of times a day:

```
Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/data/<app name>/cache/journal.tmp to /data/data/<app name>/cache/journal
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.io.IOException: failed to rename /data/data/<app name>/cache/journal.tmp to /data/data/<app name>/cache/journal
       at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java:85)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:409)
       at com.squareup.okhttp.internal.DiskLruCache.access$400(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

Using okhttp 2.5.0 and picasso 2.5.2

**Comment by swankjesse** [comment]
@metcorne can you reproduce this reliably? What file system + OS?

**Comment by metcorne** [comment]
I cannot reproduce it 100%, it just happens when i'm testing and developing my app. Sometime a couple of times a day, some days none.
Today i've seen it on these devices used by our testers;
Sony Xperia Z5 Android 5.1.1
Samsung GT P5210 Android 4.3
Samsung Galaxy Android 4.4.1

All developer devices so not many apps or no free storage.
We use Picasso and OkHttp, but i'm not sure it has anything to do with Picasso, the crash log is not very descriptive.

**Comment by swankjesse** [comment]
@metcorne cool. Will attempt to reproduce.

**Comment by grschroe** [comment]
I was experiencing this using okhttp 2.5.0 with picasso 2.3.4 and retrofit 1.9.0  I have since removed picasso completely however I see this error pop up quite a bit in my crashalytics data. This is by far the most frequent crash inside my app so im hoping this issue will be tracked down soon.

**Comment by swankjesse** [comment]
@grschroe if you can provide a reliable way to reproduce this, that’ll make it significantly easier for me to fix it.

**Comment by pristalovpavel** [comment]
Does anybody have a stable workaround? This is one of the most often crash in my app!

**Comment by xinthink** [comment]
Experiencing this with okhttp 2.6.0, on Android 5.x
shared stacktrace: http://crashes.to/s/e7df164324f

**Comment by afchamorro** [comment]
I have the same problem in my app with okhttp 2.7.0 and picasso 2.5.2, on Android 2.x, 4.x and 5.x

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/data/PACKAGE/cache/journal.tmp to /data/data/PACKAGE/cache/journal
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.io.IOException: failed to rename /data/data/PACKAGE/cache/journal.tmp to /data/data/PACKAGE/cache/journal
       at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java:85)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:409)
       at com.squareup.okhttp.internal.DiskLruCache.access$400(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Any solution?

Thank you.

**Comment by swankjesse** [comment]
@afchamorro full disk?

**Comment by afchamorro** [comment]
@swankjesse  According Crashlytics reports does not seem that's the problem.

**Comment by swankjesse** [comment]
@afchamorro big plans to improve fault tolerance in the disk cache in OkHttp 3.1.

**Comment by swankjesse** [comment]
(Late January at the earliest

**Comment by parahall** [comment]
Having the  same issue. Crash #3 among all the crashes
OkHttp 2.7.0,  12k CRASHES from 6746 USERS


Fatal Exception: java.lang.RuntimeException
java.io.IOException: failed to rename /data/user/0/com.gettaxi.dbx.android/cache/http-cache/journal.tmp to /data/user/0/com.gettaxi.dbx.android/cache/http-cache/journal
 raw

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/user/0/PACKAGE/cache/http-cache/journal.tmp to /data/user/0/PACKAGE/cache/http-cache/journal
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.io.IOException: failed to rename /data/user/0/PACKAGE/cache/http-cache/journal.tmp to /data/user/0/PACKAGE/cache/http-cache/journal
       at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java:85)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:410)
       at com.squareup.okhttp.internal.DiskLruCache.access$400(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by crossle** [comment]
Many this error

**Comment by afchamorro** [comment]
Having the same issue with OkHttp 3.1.1

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/data/PACKAGE/app_service_api_cache/journal.tmp to /data/data/PACKAGE/app_service_api_cache/journal
       at okhttp3.internal.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.io.IOException: failed to rename /data/data/PACKAGE/app_service_api_cache/journal.tmp to /data/data/PACKAGE/app_service_api_cache/journal
       at okhttp3.internal.io.FileSystem$1.rename(FileSystem.java:85)
       at okhttp3.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:405)
       at okhttp3.internal.DiskLruCache.access$400(DiskLruCache.java:84)
       at okhttp3.internal.DiskLruCache$1.run(DiskLruCache.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by matthewrice345** [comment]
We still see this error on 3.1.2 as well. 

`Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to rename /data/data/com.instructure.candroid/cache/responses/journal to /data/data/com.instructure.candroid/cache/responses/journal.bkp
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:181)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.io.IOException: failed to rename /data/data/com.instructure.candroid/cache/responses/journal to /data/data/com.instructure.candroid/cache/responses/journal.bkp
       at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java:85)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:407)
       at com.squareup.okhttp.internal.DiskLruCache.access$400(DiskLruCache.java:88)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

Our implementation is open source if that helps. https://github.com/instructure/CanvasAPI

**Comment by duanbo1983** [comment]
Seeing this on okhttp 2.7.2

**Comment by PaulProject** [comment]
error continues to 3.2.0

**Comment by dave-r12** [comment]
FWIW, I've opened up a pull request #2388 to allow the DiskLruCache to recover from this scenario. It may take some time to iron out all the details though.

**Comment by maxsdev** [comment]
Seeing this on okhttp 3.11.0 :(

**Comment by TapanM** [comment]
Same is happening.

**Comment by ningjiaqi** [comment]
how to fix, I use retrofit, same problem, update to 2.5.0, no effect

**Comment by dave-r12** [comment]
@maxsdev @TapanM @ningjiaqi could you post your stack trace?

**Comment by telemaxx** [comment]
okhttp-3.12.1 and okio 2.2.1

Feb 10, 2019 3:05:35 PM okhttp3.internal.platform.Platform log
WARNUNG: DiskLruCache C:\Users\top\AppData\Local\Temp\vtm-cache is corrupt: failed to rename C:\Users\top\AppData\Local\Temp\vtm-cache\journal to C:\Users\top\AppData\Local\Temp\vtm-cache\journal.bkp, removing
java.io.IOException: failed to rename C:\Users\top\AppData\Local\Temp\vtm-cache\journal to C:\Users\top\AppData\Local\Temp\vtm-cache\journal.bkp
	at okhttp3.internal.io.FileSystem$1.rename(FileSystem.java:85)
	at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:421)
	at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.java:305)
	at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:228)
	at okhttp3.internal.cache.DiskLruCache.edit(DiskLruCache.java:463)
	at okhttp3.internal.cache.DiskLruCache.edit(DiskLruCache.java:459)
	at okhttp3.Cache.put(Cache.java:249)
	at okhttp3.Cache$1.put(Cache.java:149)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:131)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at org.oscim.tiling.source.OkHttpEngine.sendRequest(OkHttpEngine.java:87)
	at org.oscim.tiling.source.UrlTileDataSource.query(UrlTileDataSource.java:81)
	at org.oscim.tiling.OverzoomTileDataSource.query(OverzoomTileDataSource.java:38)
	at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:135)
	at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
	at org.oscim.utils.PausableThread.run(PausableThread.java:141)

**Comment by kevinROctavian** [comment]
still get this error from okhttp:3.13.1.

Caused by java.io.IOException
failed to rename /data/user/0/com.goodboystudios.petparade/cache/picasso-cache/journal.tmp to /data/user/0/com.goodboystudios.petparade/cache/picasso-cache/journal

com.squareup.okhttp.internal.io.FileSystem$1.rename (FileSystem.java:85)

**Comment by Shimingli** [comment]
![image](https://user-images.githubusercontent.com/20720544/60424008-faf93280-9c21-11e9-9bee-b1e195d9c528.png)
help me
